// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rishvi.Modules.Core.Data;

namespace Rishvi.Migrations
{
    [DbContext(typeof(RishviDbContext))]
    [Migration("20200917171906_UpdateLableLogTable")]
    partial class UpdateLableLogTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rishvi.Modules.Linn.Models.linnUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysLeft")
                        .HasColumnType("int");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccountHolder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinnToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxImagesPerStockItem")
                        .HasColumnType("int");

                    b.Property<string>("Md5Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PushServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Server")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionUserId")
                        .HasColumnType("int");

                    b.Property<bool>("SuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isMainUser")
                        .HasColumnType("bit");

                    b.Property<bool>("isSubscribed")
                        .HasColumnType("bit");

                    b.Property<bool>("isTrial")
                        .HasColumnType("bit");

                    b.Property<int>("noOfUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("subscribedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("linnUser");
                });

            modelBuilder.Entity("Rishvi.Modules.Users.Models.GenerateLabelCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DHLrequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DHLresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Iserror")
                        .HasColumnType("bit");

                    b.Property<string>("Labelid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linnrequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linnresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orderid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orderreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenerateLabelCount");
                });

            modelBuilder.Entity("Rishvi.Modules.Users.Models.GeneratelabelLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DHLrequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DHLresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Iserror")
                        .HasColumnType("bit");

                    b.Property<string>("Labelid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linnrequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linnresponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orderid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orderreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeneratelabelLog");
                });

            modelBuilder.Entity("Rishvi.Modules.Users.Models.LabelLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("GenerateLabelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GeneratelabelLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratelabelLogId");

                    b.ToTable("LabelLogs");
                });

            modelBuilder.Entity("Rishvi.Modules.Users.Models.LabelLogs", b =>
                {
                    b.HasOne("Rishvi.Modules.Users.Models.GeneratelabelLog", "GeneratelabelLog")
                        .WithMany()
                        .HasForeignKey("GeneratelabelLogId");
                });
#pragma warning restore 612, 618
        }
    }
}
